default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: homebase_dev

test:
  <<: *default
  database: homebase_test

production:
  <<: *default
  database: homebase_prod
